package(default_visibility = ["//visibility:public"])

cc_library(
    name = "Shader",
    srcs = ["Shader.cc"],
    hdrs = ["Shader.h"],
    deps = [
        "//src:Light",
        "//src/materials:Material",
        "//src/utils:RGBColor",
        "//src/utils:ShadeRec",
    ]
)