package(default_visibility = ["//visibility:public"])

cc_library(
    name = "Shader",
    srcs = ["Shader.cc"],
    hdrs = ["Shader.h"],
    deps = [
        "//:Light",
        "//utils:RGBColor",
        "//utils:ShadeRec",
    ]
)