package(default_visibility = ["//visibility:public"])

cc_library(
    name = "Material",
    srcs = ["Material.cc"],
    hdrs = ["Material.h"],
    deps = [
        "//src/utils:RGBColor",
        "//src/utils:Vec3",
    ]
)