package(default_visibility = ["//visibility:public"])

cc_library(
    name = "loadMeshes",
    srcs = ["loadMeshes.cc"],
    hdrs = ["loadMeshes.h"],
    deps = [
        "//src/geometricObjects:Triangle",
        "//src/utils:Vec3",
    ]
)